/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Component;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author luisgm
 */
public class ClientFrame extends javax.swing.JFrame implements Frame {

    private Client client;

    DefaultListModel modeloLista;
    Component frame = null;//jOptionPane

    /**
     * Creates new form ClientFrame
     */
    public ClientFrame() {

        initComponents();
        modeloLista = new DefaultListModel();
        statusList.setModel(new DefaultListModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLanguagePanel = new javax.swing.JPanel();
        svenskabutton = new javax.swing.JButton();
        englishButton = new javax.swing.JButton();
        spanishButton = new javax.swing.JButton();
        jLoginPanel = new javax.swing.JPanel();
        jPasswordField = new javax.swing.JPasswordField();
        jUserField = new javax.swing.JTextField();
        ipAdressTxt = new javax.swing.JTextField();
        portTxt = new javax.swing.JTextField();
        jAdresslb = new javax.swing.JLabel();
        jPortlb = new javax.swing.JLabel();
        connectButton = new javax.swing.JButton();
        logginButton = new javax.swing.JButton();
        JlbCard = new javax.swing.JLabel();
        jlbCode = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jlbLanguage = new javax.swing.JLabel();
        jTransactionPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        statusList = new javax.swing.JList();
        JRefresh = new javax.swing.JButton();
        jDrawButton = new javax.swing.JButton();
        jCash = new javax.swing.JTextField();
        jLogOutButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlAmount1 = new javax.swing.JLabel();
        Securitilb = new javax.swing.JLabel();
        jCodeTxt = new javax.swing.JTextField();
        jlBalance = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBalanceOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyATM By luisgm@kth.se");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setName("JVentanaCliente"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLanguagePanel.setMaximumSize(new java.awt.Dimension(600, 400));
        jLanguagePanel.setMinimumSize(new java.awt.Dimension(0, 0));
        jLanguagePanel.setName("JVentanaSpråk"); // NOI18N
        jLanguagePanel.setPreferredSize(new java.awt.Dimension(600, 400));
        jLanguagePanel.setSize(591, 360);

        svenskabutton.setText("Svenska");
        svenskabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svenskabuttonActionPerformed(evt);
            }
        });

        englishButton.setText("English");
        englishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishButtonActionPerformed(evt);
            }
        });

        spanishButton.setText("Español");
        spanishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spanishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLanguagePanelLayout = new javax.swing.GroupLayout(jLanguagePanel);
        jLanguagePanel.setLayout(jLanguagePanelLayout);
        jLanguagePanelLayout.setHorizontalGroup(
            jLanguagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLanguagePanelLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(jLanguagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(englishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spanishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(svenskabutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jLanguagePanelLayout.setVerticalGroup(
            jLanguagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLanguagePanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(spanishButton)
                .addGap(6, 6, 6)
                .addComponent(svenskabutton)
                .addGap(6, 6, 6)
                .addComponent(englishButton)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        getContentPane().add(jLanguagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLoginPanel.setMaximumSize(new java.awt.Dimension(600, 400));
        jLoginPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        jLoginPanel.setName("JPanelLogin"); // NOI18N
        jLoginPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        jPasswordField.setText("jPasswordField1");
        jPasswordField.setEnabled(false);
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jUserField.setText("Card number");
        jUserField.setEnabled(false);
        jUserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserFieldActionPerformed(evt);
            }
        });

        ipAdressTxt.setText("localhost");

        portTxt.setText("8080");
        portTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portTxtActionPerformed(evt);
            }
        });

        jAdresslb.setText("Ip Adress:");

        jPortlb.setText("Port :");

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        logginButton.setText("Login");
        logginButton.setEnabled(false);
        logginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logginButtonActionPerformed(evt);
            }
        });

        JlbCard.setText("Card number");

        jlbCode.setText("Pin code");

        jlbLanguage.setText("En");

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jSeparator4))
                        .addGroup(jLoginPanelLayout.createSequentialGroup()
                            .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLoginPanelLayout.createSequentialGroup()
                                    .addGap(243, 243, 243)
                                    .addComponent(logginButton))
                                .addGroup(jLoginPanelLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jAdresslb)
                                    .addGap(6, 6, 6)
                                    .addComponent(ipAdressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPortlb)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(portTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jlbLanguage)
                                    .addGap(17, 17, 17)
                                    .addComponent(connectButton))
                                .addGroup(jLoginPanelLayout.createSequentialGroup()
                                    .addGap(156, 156, 156)
                                    .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jLoginPanelLayout.createSequentialGroup()
                                            .addComponent(jlbCode)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jLoginPanelLayout.createSequentialGroup()
                                            .addComponent(JlbCard)
                                            .addGap(18, 18, 18)
                                            .addComponent(jUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(0, 15, Short.MAX_VALUE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlbCard)
                    .addComponent(jUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCode)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(logginButton)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jAdresslb))
                    .addComponent(ipAdressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(portTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPortlb))
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(connectButton)
                            .addComponent(jlbLanguage)))))
        );

        jLoginPanel.setVisible(false);

        getContentPane().add(jLoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTransactionPanel.setMaximumSize(new java.awt.Dimension(600, 400));
        jTransactionPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        jTransactionPanel.setName("JPanelTransaction"); // NOI18N
        jTransactionPanel.setPreferredSize(new java.awt.Dimension(600, 400));
        jTransactionPanel.setVisible(false);

        jScrollPane4.setViewportView(statusList);

        JRefresh.setText("Refresh");
        JRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRefreshActionPerformed(evt);
            }
        });

        jDrawButton.setText("Withdrawal");
        jDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDrawButtonActionPerformed(evt);
            }
        });

        jCash.setText("Amount");
        jCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCashActionPerformed(evt);
            }
        });

        jLogOutButton.setText("Log out");
        jLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutButtonActionPerformed(evt);
            }
        });

        jlAmount1.setText("Amount:");

        Securitilb.setText("Security code");

        jCodeTxt.setText("code");
        jCodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodeTxtActionPerformed(evt);
            }
        });

        jlBalance.setText("Balance: ");

        jBalanceOut.setText("Balance");

        javax.swing.GroupLayout jTransactionPanelLayout = new javax.swing.GroupLayout(jTransactionPanel);
        jTransactionPanel.setLayout(jTransactionPanelLayout);
        jTransactionPanelLayout.setHorizontalGroup(
            jTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTransactionPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTransactionPanelLayout.createSequentialGroup()
                        .addGroup(jTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDrawButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jTransactionPanelLayout.createSequentialGroup()
                                .addComponent(jlAmount1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCash, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Securitilb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jTransactionPanelLayout.createSequentialGroup()
                                .addComponent(jlBalance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBalanceOut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTransactionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLogOutButton)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(55, 55, 55))))
        );
        jTransactionPanelLayout.setVerticalGroup(
            jTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTransactionPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRefresh)
                    .addComponent(jlBalance)
                    .addComponent(jLabel6)
                    .addComponent(jBalanceOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDrawButton)
                    .addComponent(jCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAmount1)
                    .addComponent(Securitilb)
                    .addComponent(jCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLogOutButton)
                .addGap(51, 51, 51))
        );

        getContentPane().add(jTransactionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>                        

    private void svenskabuttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        new Thread(new Runnable() {

            public void run() {
                jLanguagePanel.setVisible(false);
                logginButton.setText("Logga in");
                jlbCode.setText("Pin kod");
                JlbCard.setText("Kortnummer");
                connectButton.setText("Ansluta");
                jlbLanguage.setText("Sv");
                jlBalance.setText("Saldo:");
                jBalanceOut.setText("");
                JRefresh.setText("Uppdatera");
                Securitilb.setText("Säkerhetskod");
                jlAmount1.setText("Belopp: ");
                jLogOutButton.setText("Logga ut");
                jDrawButton.setText("Uttag");
                jLoginPanel.setVisible(true);
            }
        }).start();


    }                                             

    private void spanishButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        new Thread(new Runnable() {
            public void run() {
                jLanguagePanel.setVisible(false);
                logginButton.setText("Ingresar");
                jlbCode.setText("Codigo pin");
                JlbCard.setText("Numero de tarjeta");
                connectButton.setText("Conectar");
                jlbLanguage.setText("Es");
                jlBalance.setText("Saldo:");
                JRefresh.setText("Refrescar");
                jBalanceOut.setText("");
                jDrawButton.setText("Retiro");
                jlAmount1.setText("Monto: ");
                Securitilb.setText("Código de seguridad");

                jLogOutButton.setText("Cierra sesión");
                jLoginPanel.setVisible(true);
            }
        }).start();

    }                                             

    private void englishButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        jLanguagePanel.setVisible(false);
        jLoginPanel.setVisible(true);
    }                                             

    private void portTxtActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        new Thread(new Runnable() {
            public void run() {
                String flag = jlbLanguage.getText();
                String ip = ipAdressTxt.getText();
                String connect = "1";
                int port = Integer.parseInt(portTxt.getText());
                TransactionInterface trans = new Transaction(connect, flag);
                client = new Client();
                client.accessServer(ip, port);
                String msg = client.MakeTransac(trans);
                String[] msgList = msg.split(",");
                switch (msg) {
                    case "Connected":
                        logginButton.setEnabled(true);
                        jUserField.setEnabled(true);
                        jPasswordField.setEnabled(true);
                        connectButton.setVisible(false);
                        ipAdressTxt.setVisible(false);
                        portTxt.setVisible(false);
                        jPortlb.setVisible(false);
                        jAdresslb.setVisible(false);
                        jlbLanguage.setVisible(false);

                        notifyStatus(msg);

                }
            }
        }).start();

    }                                             

    private void logginButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        new Thread(new Runnable() {
            public void run() {
                String login = "2";//Transaction Type
                String cn = jUserField.getText();//Get User
                char[] pss = jPasswordField.getPassword();//Get Password

                //Create a new transaction
                TransactionInterface trans = new Transaction(login, cn, pss);
                //Create a new string and Calls MakeTransaction 
                String msg = client.MakeTransac(trans);
                //Split the message
                String[] msgList = msg.split(",");
                switch (msgList[0]) {
                    case "Valid":
                        jLanguagePanel.setVisible(false);
                        jLoginPanel.setVisible(false);
                        jTransactionPanel.setVisible(true);
                        notifyStatus(msgList[1]);
                        break;
                    case "NoValid"://pass novalid
                        switch (msgList[1]) {
                            case "Sv":
                                JOptionPane.showMessageDialog(frame, "Ogiltit Password");
                                break;
                            case "Es"://Spanish
                                JOptionPane.showMessageDialog(frame, "Contraseña no valida");
                                break;
                            case "En"://English
                                JOptionPane.showMessageDialog(frame, "No valid Password");
                                break;
                        }
                }
            }
        }
        ).start();

    }                                            

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:

    }                                              

    private void jUserFieldActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:

    }                                          

    private void JRefreshActionPerformed(java.awt.event.ActionEvent evt) {                                         
        new Thread(new Runnable() {
            public void run() {
                String refresh = "6";
                TransactionInterface trans = new Transaction(refresh, "", "");
                String msg = client.MakeTransac(trans);
                notifyStatus(msg);
            }
        }).start();


    }                                        

    private void jCashActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void jCodeTxtActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        new Thread(new Runnable() {
            public void run() {
                String withdraw = "3";
                String amount = jCash.getText();
                String code = jCodeTxt.getText();;

                TransactionInterface trans = new Transaction(withdraw, amount, code);
                jCash.setText("");
                jCodeTxt.setText("");;
                String msg = client.MakeTransac(trans);
                String[] msgList = msg.split(",");

                switch (msgList[0]) {
                    case "Valid":
                        notifyStatus("Tips: " + msgList[1]);
                        jBalanceOut.setText(msgList[2]);
                        break;
                    case "NoValid"://Balanse No valid
                        switch (msgList[1]) {
                            case "Sv"://Svenska
                                JOptionPane.showMessageDialog(frame, "Uttag medges ej");
                                break;
                            case "Es"://Spanish
                                JOptionPane.showMessageDialog(frame, "Retiro no permitido");
                                break;
                            case "En"://English
                                JOptionPane.showMessageDialog(frame, "Withdrawals are not granted.");
                                break;
                        }
                }

            }
        }).start();


    }                                           

    private void jLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        client.Disconnect("4");
        System.exit(1);
    }                                             

    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        client.Disconnect("5");
        System.exit(1);
    }                                  

    @Override
    public void notifyStatus(String status) {
        System.out.println("Notifying...");
        //New Event Date 
        DateFormat formatoFecha = DateFormat.getDateTimeInstance();
        String fecha = formatoFecha.format(new Date());
        //Status message
        String mensaje = fecha + ": " + status;
        //Get info and add new status
        modeloLista = (DefaultListModel) statusList.getModel();
        modeloLista.addElement(mensaje);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                init();
            }

            private void init() {
                new ClientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton JRefresh;
    private javax.swing.JLabel JlbCard;
    private javax.swing.JLabel Securitilb;
    private javax.swing.JButton connectButton;
    private javax.swing.JButton englishButton;
    private javax.swing.JTextField ipAdressTxt;
    private javax.swing.JLabel jAdresslb;
    private javax.swing.JLabel jBalanceOut;
    private javax.swing.JTextField jCash;
    private javax.swing.JTextField jCodeTxt;
    private javax.swing.JButton jDrawButton;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jLanguagePanel;
    private javax.swing.JButton jLogOutButton;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel jPortlb;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel jTransactionPanel;
    private javax.swing.JTextField jUserField;
    private javax.swing.JLabel jlAmount1;
    private javax.swing.JLabel jlBalance;
    private javax.swing.JLabel jlbCode;
    private javax.swing.JLabel jlbLanguage;
    private javax.swing.JButton logginButton;
    private javax.swing.JTextField portTxt;
    private javax.swing.JButton spanishButton;
    public javax.swing.JList statusList;
    private javax.swing.JButton svenskabutton;
    // End of variables declaration                   
}
